name: CI Practice

on:
  push:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: check out
        uses: actions/checkout@v4


      - name: run test
        run: echo "GitHub Action is Working"

      - name: Run real test
        run: ./test.sh
